# Combining Harris Crime CSV Files

In [1]:
# Importing Dependencies 
import pandas as pd

## Check CSV Files

In [3]:
# Load Oct-Dec 2021 DF
oct_dec_2021_df = pd.read_csv("Oct_Dec_2021_Houston_Police_Department_report.csv")
oct_dec_2021_df.head()

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,985322,"01/01/2022, 12:00:00 AM","01/04/2022, 1:38:03 PM",HOUSTON,TX,77036,9000 Block BEECHNUT ST,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
1,1124522,"12/31/2021, 3:00:00 PM","01/04/2022, 1:38:47 PM",HOUSTON,TX,77099,11700 Block BASILICA ST,Aggravated Assault,Assault,Aggravated Assault
2,1131722,"12/31/2021, 5:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77077,11900 Block OVERBROOK LN,Intimidation,Other,Intimidation
3,997722,"12/31/2021, 11:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77037,9600 Block NORTH FWY,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
4,1089322,"12/31/2021, 1:00:00 PM","01/04/2022, 10:19:13 AM",HOUSTON,TX,77077,2000 Block BENTWORTH DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"

In [4]:
# Load Jan-Mar 2022 DF
jan_mar_2022_df = pd.read_csv("Jan_Mar_2022_Houston_Police_Department_report.csv")
jan_mar_2022_df.head()

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,43803222,"03/31/2022, 7:00:00 PM","04/04/2022, 12:37:55 PM",HOUSTON,TX,77016,10300 Block WICKLOWE ST,Theft of motor vehicle parts or accessory,Theft from Vehicle,Theft of motor vehicle parts or accessory
1,43792722,"04/01/2022, 5:00:00 AM","04/04/2022, 12:37:41 PM",HOUSTON,TX,77055,1300 Block POST OAK RD N,Theft of motor vehicle parts or accessory,Theft from Vehicle,Theft of motor vehicle parts or accessory
2,43819822,"04/01/2022, 12:00:00 AM","04/04/2022, 12:37:55 PM",HOUSTON,TX,77002,3800 Block MAIN ST,Motor vehicle theft,Theft of Vehicle,Motor vehicle theft
3,43716522,"04/01/2022, 1:00:00 AM","04/04/2022, 7:08:52 AM",HOUSTON,TX,77057,5800 Block INWOOD DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
4,42942122,"04/01/2022, 6:00:00 AM","04/04/2022, 7:09:25 AM",HOUSTON,TX,77047,3800 Block HICKOK LN,Simple assault,Assault,Simple assault

In [5]:
# Load Apr-Jun 2022 DF
apr_jun_2022_df = pd.read_csv("Apr_Jun_2022_Houston_Police_Department_report.csv")
apr_jun_2022_df.head()

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,86649322,"07/01/2022, 12:00:00 AM","07/04/2022, 12:38:20 PM",HOUSTON,TX,77093,9600 Block DODSON ST,Prostitution,Other,Prostitution
1,88070322,"06/30/2022, 11:00:00 PM","07/04/2022, 12:38:00 PM",HOUSTON,TX,77005,5600 Block SHEPHERD DR N,Motor vehicle theft,Theft of Vehicle,Motor vehicle theft
2,88014322,"07/01/2022, 5:00:00 AM","07/04/2022, 12:38:00 PM",HOUSTON,TX,77042,3000 Block SEAGLER RD,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
3,86763622,"07/01/2022, 5:00:00 AM","07/04/2022, 12:38:16 PM",HOUSTON,TX,77019,1200 Block WAUGH DR,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
4,88055422,"06/30/2022, 4:00:00 PM","07/04/2022, 12:38:05 PM",HOUSTON,TX,77026,4300 Block WOOLWORTH,All other larceny,Other,All other larceny

In [6]:
# Load Jul-Sep 2022 DF
jul_sep_2022_df = pd.read_csv("Jul_Sep_2022_Houston_Police_Department_report.csv")
jul_sep_2022_df

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,132038222,"09/30/2022, 10:00:00 AM","10/01/2022, 3:37:23 PM",HOUSTON,TX,77098,2000 Block SUL ROSS,Motor vehicle theft,Theft of Vehicle,Motor vehicle theft
1,132325522,"10/01/2022, 6:00:00 AM","10/01/2022, 3:37:24 PM",HOUSTON,TX,77006,900 Block WESTHEIMER RD,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
2,132307222,"10/01/2022, 6:00:00 AM","10/01/2022, 3:37:24 PM",HOUSTON,TX,77004,2900 Block BLODGETT ST,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
3,132305122,"10/01/2022, 6:00:00 AM","10/01/2022, 3:37:23 PM",HOUSTON,TX,77089,11600 Block GULF POINTE DR,Simple assault,Assault,Simple assault
4,132262222,"10/01/2022, 4:00:00 AM","10/01/2022, 3:37:23 PM",HOUSTON,TX,77060,100 Block ALDINE BENDER RD,Simple assault,Assault,Simple assault
...,...,...,...,...,...,...,...,...,...,...
51356,86781522,"07/01/2022, 8:00:00 AM","07/01/2022, 11:38:38 PM",HOUSTON,TX,77042,11200 Block BRIAR FOREST DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
51357,86770422,"07/01/2022, 8:00:00 AM","07/01/2022, 11:38:35 PM",HOUSTON,TX,77093,8500 Block EASTEX FWY,All other larceny,Other,All other larceny
51358,86780122,"07/01/2022, 8:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77072,10000 Block BEECHNUT ST,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
51359,86763522,"07/01/2022, 7:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77040,13800 Block NORTHWEST FWY,All other larceny,Other,All other larceny
51360,86763022,"07/01/2022, 7:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77076,100 Block BRENDA ST W,All other offenses,Other,All other offenses

In [7]:
# Merging 0ct and Jan Dfs
merged_df = oct_dec_2021_df.append(jan_mar_2022_df, ignore_index = True)
merged_df

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,985322,"01/01/2022, 12:00:00 AM","01/04/2022, 1:38:03 PM",HOUSTON,TX,77036,9000 Block BEECHNUT ST,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
1,1124522,"12/31/2021, 3:00:00 PM","01/04/2022, 1:38:47 PM",HOUSTON,TX,77099,11700 Block BASILICA ST,Aggravated Assault,Assault,Aggravated Assault
2,1131722,"12/31/2021, 5:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77077,11900 Block OVERBROOK LN,Intimidation,Other,Intimidation
3,997722,"12/31/2021, 11:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77037,9600 Block NORTH FWY,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
4,1089322,"12/31/2021, 1:00:00 PM","01/04/2022, 10:19:13 AM",HOUSTON,TX,77077,2000 Block BENTWORTH DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
...,...,...,...,...,...,...,...,...,...,...
98568,26422,"01/01/2022, 7:00:00 AM","01/01/2022, 6:38:05 PM",HOUSTON,TX,77054,9900 Block BUFFALO SPEEDWAY,All other offenses,Other,All other offenses
98569,22922,"01/01/2022, 7:00:00 AM","01/01/2022, 6:38:03 PM",HOUSTON,TX,77023,1800 Block PASADENA,Disorderly conduct,Quality of Life,Disorderly conduct
98570,43422,"01/01/2022, 7:00:00 AM","01/01/2022, 6:38:09 PM",HOUSTON,TX,77051,4500 Block BRISCOE ST,Disorderly conduct,Quality of Life,Disorderly conduct
98571,23022,"01/01/2022, 7:00:00 AM","01/01/2022, 6:38:04 PM",HOUSTON,TX,77096,6300 Block DUMFRIES DR,Aggravated Assault,Assault,Aggravated Assault
98572,15122,"01/01/2022, 7:00:00 AM","01/01/2022, 6:38:02 PM",HOUSTON,TX,77011,6500 Block AVENUE J,All other offenses,Other,All other offenses

In [8]:
# Merge merged_df and Apr Dfs
merged_df = merged_df.append(apr_jun_2022_df, ignore_index = True)
merged_df

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,985322,"01/01/2022, 12:00:00 AM","01/04/2022, 1:38:03 PM",HOUSTON,TX,77036,9000 Block BEECHNUT ST,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
1,1124522,"12/31/2021, 3:00:00 PM","01/04/2022, 1:38:47 PM",HOUSTON,TX,77099,11700 Block BASILICA ST,Aggravated Assault,Assault,Aggravated Assault
2,1131722,"12/31/2021, 5:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77077,11900 Block OVERBROOK LN,Intimidation,Other,Intimidation
3,997722,"12/31/2021, 11:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77037,9600 Block NORTH FWY,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
4,1089322,"12/31/2021, 1:00:00 PM","01/04/2022, 10:19:13 AM",HOUSTON,TX,77077,2000 Block BENTWORTH DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
...,...,...,...,...,...,...,...,...,...,...
149767,42498422,"04/01/2022, 7:00:00 AM","04/01/2022, 10:44:02 PM",HOUSTON,TX,77530,12600 Block GREEN DR S,"Burglary, Breaking and Entering",Breaking & Entering,"Burglary, Breaking and Entering"
149768,42498222,"04/01/2022, 7:00:00 AM","04/01/2022, 10:44:01 PM",HOUSTON,TX,77009,2400 Block FULTON ST,"Burglary, Breaking and Entering",Breaking & Entering,"Burglary, Breaking and Entering"
149769,42495022,"04/01/2022, 7:00:00 AM","04/01/2022, 2:37:24 PM",HOUSTON,TX,77026,5100 Block KASHMERE ST,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
149770,42494922,"04/01/2022, 7:00:00 AM","04/01/2022, 2:37:23 PM",HOUSTON,TX,77099,11000 Block KINGHURST DR,Aggravated Assault,Assault,Aggravated Assault
149771,42492222,"04/01/2022, 7:00:00 AM","04/01/2022, 2:37:23 PM",HOUSTON,TX,77057,3700 Block HILLCROFT AVE,Robbery,Robbery,Robbery

In [9]:
# Merge merged_df and July
merged_df = merged_df.append(jul_sep_2022_df, ignore_index = True)
merged_df

,ccn,date,updateDate,city,state,postalCode,blocksizedAddress,incidentType,parentIncidentType,narrative
0,985322,"01/01/2022, 12:00:00 AM","01/04/2022, 1:38:03 PM",HOUSTON,TX,77036,9000 Block BEECHNUT ST,Theft from motor vehicle,Theft from Vehicle,Theft from motor vehicle
1,1124522,"12/31/2021, 3:00:00 PM","01/04/2022, 1:38:47 PM",HOUSTON,TX,77099,11700 Block BASILICA ST,Aggravated Assault,Assault,Aggravated Assault
2,1131722,"12/31/2021, 5:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77077,11900 Block OVERBROOK LN,Intimidation,Other,Intimidation
3,997722,"12/31/2021, 11:00:00 PM","01/04/2022, 10:45:17 AM",HOUSTON,TX,77037,9600 Block NORTH FWY,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
4,1089322,"12/31/2021, 1:00:00 PM","01/04/2022, 10:19:13 AM",HOUSTON,TX,77077,2000 Block BENTWORTH DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
...,...,...,...,...,...,...,...,...,...,...
201128,86781522,"07/01/2022, 8:00:00 AM","07/01/2022, 11:38:38 PM",HOUSTON,TX,77042,11200 Block BRIAR FOREST DR,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
201129,86770422,"07/01/2022, 8:00:00 AM","07/01/2022, 11:38:35 PM",HOUSTON,TX,77093,8500 Block EASTEX FWY,All other larceny,Other,All other larceny
201130,86780122,"07/01/2022, 8:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77072,10000 Block BEECHNUT ST,"Destruction, damage, vandalism",Property Crime,"Destruction, damage, vandalism"
201131,86763522,"07/01/2022, 7:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77040,13800 Block NORTHWEST FWY,All other larceny,Other,All other larceny
201132,86763022,"07/01/2022, 7:00:00 AM","07/01/2022, 3:39:02 PM",HOUSTON,TX,77076,100 Block BRENDA ST W,All other offenses,Other,All other offenses

In [10]:
# Check size of DF
merged_df.count()

ccn                   201133
date                  201133
updateDate            201133
city                  201133
state                 201133
postalCode            201133
blocksizedAddress     201133
incidentType          201133
parentIncidentType    201133
narrative             201133
dtype: int64

In [11]:
# Check columns
merged_df.columns

Index(['ccn', 'date', 'updateDate', 'city', 'state', 'postalCode',
       'blocksizedAddress', 'incidentType', 'parentIncidentType', 'narrative'],
      dtype='object')

In [12]:
# Check types 
merged_df.dtypes

ccn                    int64
date                  object
updateDate            object
city                  object
state                 object
postalCode            object
blocksizedAddress     object
incidentType          object
parentIncidentType    object
narrative             object
dtype: object

In [13]:
# Drop CCN column
merged_df.drop(['ccn', 'updateDate', 'blocksizedAddress', 'incidentType', 'narrative'], axis = 1)

                           date     city state postalCode  parentIncidentType
0       01/01/2022, 12:00:00 AM  HOUSTON    TX      77036  Theft from Vehicle
1        12/31/2021, 3:00:00 PM  HOUSTON    TX      77099             Assault
2        12/31/2021, 5:00:00 PM  HOUSTON    TX      77077               Other
3       12/31/2021, 11:00:00 PM  HOUSTON    TX      77037      Property Crime
4        12/31/2021, 1:00:00 PM  HOUSTON    TX      77077      Property Crime
...                         ...      ...   ...        ...                 ...
201128   07/01/2022, 8:00:00 AM  HOUSTON    TX      77042      Property Crime
201129   07/01/2022, 8:00:00 AM  HOUSTON    TX      77093               Other
201130   07/01/2022, 8:00:00 AM  HOUSTON    TX      77072      Property Crime
201131   07/01/2022, 7:00:00 AM  HOUSTON    TX      77040               Other
201132   07/01/2022, 7:00:00 AM  HOUSTON    TX      77076               Other

[201133 rows x 5 columns]

In [14]:
# Remake Columns
columns = ['date', 'city']

In [15]:
# Check unique values for parentincidenttype
merged_df.parentIncidentType.value_counts()

Other                    58075
Theft from Vehicle       37391
Assault                  30451
Property Crime           16925
Theft of Vehicle         15263
Theft                    13214
Breaking & Entering      11293
Quality of Life           6526
Robbery                   6231
Traffic                   5534
Fire                       227
Theft;Property Crime         1
Other                        1
Assault ;Other               1
Name: parentIncidentType, dtype: int64